### ISSUE TITLE
"[object Object]" is not valid JSON

### ISSUE THREAD

**Issue by wdarins** [yemenpoint/filament-google-map-location-picker#2]
Hi, @yemenpoint I don't know why did you rolled back my PR but right now I have again the same problem:

![image](https://user-images.githubusercontent.com/40423022/191189389-7d4fca63-ac6b-43a5-a60d-3fba6883f6c4.png)

Here is my model:
![image](https://user-images.githubusercontent.com/40423022/191189500-b86d622f-2459-4af5-a279-610a901c9b2e.png)

Here is what `this?.value` is:
![image](https://user-images.githubusercontent.com/40423022/191189853-6f5cfb0a-2e24-479b-a983-c0747779b2e4.png)
![image](https://user-images.githubusercontent.com/40423022/191189903-c4974920-de16-4713-938d-a31e2de908f6.png)

Maybe we should add a check if it's already an object then no need to `JSON.parse`?

**Comment by yemenpoint** [comment]
I will fix it sorry .😅😅

**Comment by yemenpoint** [comment]
Check the last commit

**Comment by wdarins** [comment]
Thanks, issue solved!
